version: 2
sources:
    - name: datafeed_shared_schema
      database: "{{('dbt_db')}}"
      schema: staging_layer
      tables:
        - name: stg_customerdata
        - name: stg_payments
        - name: stg_order
        - name: STG_ITEMS_DATA
        - name: STG_PRODUCT_DATA
        - name: STG_SUPPLIES_DATA
        - name : emp
        - name : customers
        - name : stg_orders
          columns:
            - name: id
              tests:
                - unique
                - not_null
            - name: status
              tests:
                - accepted_values:
                      values: ['placed', 'shipped', 'completed', 'returned', 'return_pending']

        - name : CUSTOMERS
        
